<a href="https://colab.research.google.com/github/Dawon00/Tensorflow/blob/main/%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%ED%92%88%EC%A2%85%EB%B6%84%EB%A5%98(multi_layer_%EC%B6%94%EA%B0%80).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
#과거의 데이터를 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head() #5개 보기

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
#독립변수, 종속변수
독립 = 인코딩[['꽃잎길이','꽃잎폭', '꽃받침길이','꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
#모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(5, activation='swish')(X)
H = tf.keras.layers.Dense(5, activation='swish')(H)
H = tf.keras.layers.Dense(5, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
#모델 학습(FIT)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1643 - accuracy: 0.9600
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1672 - accuracy: 0.9600
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1602 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1593 - accuracy: 0.9533
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1548 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1527 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1580 - accuracy: 0.9600
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1495 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1517 - accuracy: 0.9600
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1515 - accuracy: 0.9667


In [ ]:
#모델 학습(FIT) 더 많이!
model.fit(독립, 종속, epochs=100)

In [ ]:
#모델을 이용하기
model.predict(독립[0:5])

array([[9.9137306e-01, 8.6264331e-03, 5.6878912e-07],
       [9.8693162e-01, 1.3066573e-02, 1.7309230e-06],
       [9.8946488e-01, 1.0533652e-02, 1.4592426e-06],
       [9.8727369e-01, 1.2724281e-02, 2.0162286e-06],
       [9.9204367e-01, 7.9559265e-03, 5.2175659e-07]], dtype=float32)

In [ ]:
#실제 정답
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
#학습한 가중치
model.get_weights()

[array([[ 0.34007832, -0.10689191,  0.25493008, -0.08657203,  0.03438811],
        [ 0.30644786,  0.70156354,  0.39109337, -0.1349779 ,  0.42261425],
        [-0.2818571 , -0.08769149, -0.14075634,  0.9021053 ,  0.7842506 ],
        [-0.13583694, -0.39701173,  0.2680493 , -0.1086344 ,  0.10297666]],
       dtype=float32),
 array([ 0.24956077,  0.36797023,  0.2751998 , -0.15266997,  0.08829778],
       dtype=float32),
 array([[ 0.29856387,  0.3678174 ,  0.7246215 ,  0.9715844 , -0.933801  ],
        [-0.8097455 ,  1.0196792 ,  0.57909435, -0.338601  , -1.0706922 ],
        [-0.24244393, -0.6022371 , -0.49081698,  0.6083418 , -0.00266226],
        [ 0.5195578 , -0.56764597,  0.46305218, -0.13756329,  0.5209058 ],
        [ 0.74357885,  0.03736834, -0.7232796 ,  0.71015096,  0.8107046 ]],
       dtype=float32),
 array([-0.27465227,  0.16490316,  0.01303563,  0.29488063, -0.16023205],
       dtype=float32),
 array([[-0.30560103, -0.3595549 ,  0.36751354,  0.30336168, -0.19640529],
        